// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Error
	ErrorResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_internal_server_error ErrorCode = 500
	ErrorCode_bad_request           ErrorCode = 400
	ErrorCode_forbidden             ErrorCode = 403
	ErrorCode_not_found             ErrorCode = 404
)

var ErrorCode_name = map[int32]string{
	500: "internal_server_error",
	400: "bad_request",
	403: "forbidden",
	404: "not_found",
}
var ErrorCode_value = map[string]int32{
	"internal_server_error": 500,
	"bad_request":           400,
	"forbidden":             403,
	"not_found":             404,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Error struct {
	Code             *int32     `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Title            *ErrorCode `protobuf:"varint,2,opt,name=title,enum=nagax.router.api.ErrorCode" json:"title,omitempty"`
	Detail           *string    `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Error) GetTitle() ErrorCode {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ErrorCode_internal_server_error
}

func (m *Error) GetDetail() string {
	if m != nil && m.Detail != nil {
		return *m.Detail
	}
	return ""
}

type ErrorResponse struct {
	Errors           []*Error `protobuf:"bytes,1,rep,name=errors" json:"errors,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ErrorResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "nagax.router.api.Error")
	proto.RegisterType((*ErrorResponse)(nil), "nagax.router.api.ErrorResponse")
	proto.RegisterEnum("nagax.router.api.ErrorCode", ErrorCode_name, ErrorCode_value)
}
func (m *Error) SetCode(v *int32) {
	m.Code = v
}

func (m *Error) SetTitle(v *ErrorCode) {
	m.Title = v
}

func (m *Error) SetDetail(v *string) {
	m.Detail = v
}

func (m *ErrorResponse) SetErrors(v []*Error) {
	m.Errors = v
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xcd, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x60, 0x6a, 0xec, 0x42, 0x67, 0x71, 0x09, 0x03, 0x6a, 0xd1, 0x4b, 0xd9, 0x53, 0xf1,
	0x10, 0x71, 0x9f, 0x40, 0x10, 0x5f, 0x20, 0x37, 0x4f, 0x25, 0x6b, 0xa6, 0x12, 0x28, 0x99, 0x3a,
	0x49, 0xc5, 0xc7, 0x10, 0xf4, 0x51, 0x7d, 0x00, 0x31, 0x2e, 0x1e, 0x04, 0x6f, 0xf3, 0x0f, 0xdf,
	0x3f, 0x03, 0x8d, 0x9b, 0x83, 0x99, 0x85, 0x33, 0xa3, 0x8e, 0xee, 0xc9, 0xbd, 0x1a, 0xe1, 0x25,
	0x93, 0x18, 0x37, 0x87, 0xed, 0x08, 0xf5, 0xbd, 0x08, 0x0b, 0x22, 0x1c, 0x3f, 0xb2, 0xa7, 0xb6,
	0xea, 0xaa, 0xbe, 0xb6, 0x65, 0xc6, 0x1b, 0xa8, 0x73, 0xc8, 0x13, 0xb5, 0x47, 0x5d, 0xd5, 0x6f,
	0x76, 0x97, 0xe6, 0x6f, 0xdd, 0x94, 0xee, 0x1d, 0x7b, 0xb2, 0x3f, 0x12, 0xcf, 0x60, 0xe5, 0x29,
	0xbb, 0x30, 0xb5, 0xaa, 0xab, 0xfa, 0xc6, 0x1e, 0xd2, 0xf6, 0x16, 0x4e, 0x8a, 0xb5, 0x94, 0x66,
	0x8e, 0x89, 0xf0, 0x1a, 0x56, 0xf4, 0xbd, 0x48, 0x6d, 0xd5, 0xa9, 0x7e, 0xbd, 0x3b, 0xff, 0xe7,
	0xb8, 0x3d, 0xb0, 0xab, 0x07, 0x68, 0x7e, 0xbf, 0xe1, 0x05, 0x9c, 0x86, 0x98, 0x49, 0xa2, 0x9b,
	0x86, 0x44, 0xf2, 0x42, 0x32, 0x14, 0xa6, 0x3f, 0x15, 0x6a, 0x58, 0xef, 0x9d, 0x1f, 0x84, 0x9e,
	0x17, 0x4a, 0x59, 0xbf, 0x29, 0xdc, 0x40, 0x33, 0xb2, 0xec, 0x83, 0xf7, 0x14, 0xf5, 0x7b, 0xc9,
	0x91, 0xf3, 0x30, 0xf2, 0x12, 0xbd, 0xfe, 0x50, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x93, 0x6d,
	0x7b, 0xfd, 0x22, 0x01, 0x00, 0x00,
}
